### ISSUE TITLE
Use unsigned types where possible

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/Universal-Texture-Transcoders#7]
Use of unsigned types slightly improves the performance. Early tests show that the compiled binary remains the same with the only difference being instructions like `shr_s`, `gt_s`, etc being replaced with their unsigned counterparts. However, some code paths are faster with signed types, so further evaluation is required.

**Comment by MaxGraey** [comment]
I could help with this, but without tests it will be very difficult for me. It would be great to add tests either from the javascript side or directly to AssemblyScript via [as-pect](https://github.com/jtenner/as-pect)

**Comment by donmccurdy** [comment]
I can help with tests, if @lexaknyazev is OK with this. 🙂 My usual choice is [tape](https://github.com/substack/tape/); it's clean and simple compared to most (JS) test libraries. But I'm certainly open to other ideas. Opened a PR at #8.

**Comment by MaxGraey** [comment]
I totally fine with `tape`. Btw did you see [`ava`](https://github.com/avajs/ava)? Also pretty great fully async test framework

**Comment by donmccurdy** [comment]
ava looks totally reasonable, too! I just haven't used it before. 🤷‍♂️

**Comment by MaxGraey** [comment]
Let me know when all tests are ready)

**Comment by lexaknyazev** [comment]
@MaxGraey 
The CI is ready, should be enough to ensure correctness. We'll probably add some benchmarks later.

**Comment by MaxGraey** [comment]
Great!
